USE [master]
GO

/****** Object:  Database [Logsdb]    Script Date: 11/27/2018 9:53:44 PM ******/
CREATE DATABASE [Logsdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Logsdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SHP2016\MSSQL\DATA\Logsdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Logsdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SHP2016\MSSQL\DATA\Logsdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Logsdb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Logsdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Logsdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Logsdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Logsdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Logsdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Logsdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [Logsdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Logsdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Logsdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Logsdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Logsdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Logsdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Logsdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Logsdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Logsdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Logsdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Logsdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Logsdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Logsdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Logsdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Logsdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Logsdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Logsdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Logsdb] SET RECOVERY FULL 
GO

ALTER DATABASE [Logsdb] SET  MULTI_USER 
GO

ALTER DATABASE [Logsdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Logsdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Logsdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Logsdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Logsdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Logsdb] SET QUERY_STORE = OFF
GO

USE [Logsdb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Logsdb] SET  READ_WRITE 
GO


